// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkbciBGsy2p5CSzBS7qZoPWa_gGkU94K8',
    appId: '1:464997390171:web:20599285def6696fb12c7e',
    messagingSenderId: '464997390171',
    projectId: 'rockspaceaio',
    authDomain: 'rockspaceaio.firebaseapp.com',
    databaseURL: 'https://rockspaceaio-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rockspaceaio.appspot.com',
    measurementId: 'G-0H5F4PB2FT',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkbciBGsy2p5CSzBS7qZoPWa_gGkU94K8',
    appId: '1:464997390171:web:2c7132b0d33ac45cb12c7e',
    messagingSenderId: '464997390171',
    projectId: 'rockspaceaio',
    authDomain: 'rockspaceaio.firebaseapp.com',
    databaseURL: 'https://rockspaceaio-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rockspaceaio.appspot.com',
    measurementId: 'G-K6G8BQD2JZ',
  );
}
